export enum ECourseEditorActionTypes {
  GET_COURSE_BY_ID_REQUEST = 'COURSE_EDITOR/GET_COURSE_BY_ID_REQUEST',
  GET_COURSE_BY_ID_SUCCESS = 'COURSE_EDITOR/GET_COURSE_BY_ID_SUCCESS',
  GET_COURSE_BY_ID_FAILURE = 'COURSE_EDITOR/GET_COURSE_BY_ID_FAILURE',
}
